#include "stdafx.h"
#include "VertexLayout.h"

#define VERTEX_RG				DXGI_FORMAT_R32G32_FLOAT
#define VERTEX_RGB				DXGI_FORMAT_R32G32B32_FLOAT
#define VERTEX_RGBA				DXGI_FORMAT_R32G32B32A32_FLOAT
#define VERTEX					D3D11_INPUT_PER_VERTEX_DATA

#define ALIGNED_ELEMENT			D3D11_APPEND_ALIGNED_ELEMENT

D3D11_INPUT_ELEMENT_DESC  INPUT_ELEMENT_PARAMETER_POSITION = { "POSITION", 0, VERTEX_RGB, 0, 0,    VERTEX, 0 };
D3D11_INPUT_ELEMENT_DESC  INPUT_ELEMENT_PARAMETER_COLOR = { "COLOR", 0, VERTEX_RGBA, 0, ALIGNED_ELEMENT, VERTEX, 0 };
D3D11_INPUT_ELEMENT_DESC  INPUT_ELEMENT_PARAMETER_TEXCOORD = { "TEXCOORD", 0, VERTEX_RG, 0, ALIGNED_ELEMENT, VERTEX, 0 };
D3D11_INPUT_ELEMENT_DESC  INPUT_ELEMENT_PARAMETER_NORMAL = { "NORMAL", 0, VERTEX_RGB, 0, ALIGNED_ELEMENT, VERTEX, 0 };

D3D11_INPUT_ELEMENT_DESC PC_Vertex::desc[] =
{
	INPUT_ELEMENT_PARAMETER_POSITION,
	INPUT_ELEMENT_PARAMETER_COLOR,
};
UINT PC_Vertex::count = 2;

D3D11_INPUT_ELEMENT_DESC PT_Vertex::desc[] =
{
	INPUT_ELEMENT_PARAMETER_POSITION,
	INPUT_ELEMENT_PARAMETER_TEXCOORD,
};
UINT PT_Vertex::count = 2;

D3D11_INPUT_ELEMENT_DESC PNT_Vertex::desc[] =
{
	INPUT_ELEMENT_PARAMETER_POSITION,
	INPUT_ELEMENT_PARAMETER_TEXCOORD,
	INPUT_ELEMENT_PARAMETER_NORMAL,
};
UINT PNT_Vertex::count = 3;